### ISSUE TITLE
Support for auto_tls

### ISSUE THREAD

**Issue by werdnum** [tailscale/caddy-tailscale#19]
I was wondering what it would take to get the automatic TLS integration working properly.

I don't know too much about Caddy, but in the absence of any other mechanism for cross-server shared state, I was thinking about stuffing the tailscale Server object in a global map under the tailscale package, keyed by `tsnet.Server.CertDomains()`, and then calling `s.LocalClient.CertPair()`.

It isn't the prettiest design, but I'm welcome to other suggestions if you know of a better way to share state between the cert manager and the listener.

If you're OK with that design, I could probably whip something up over the next few days.

**Comment by mholt** [comment]
Just to clarify, what isn't working properly?

**Comment by werdnum** [comment]
I'm referring to the shortcomings mentioned here: https://github.com/tailscale/caddy-tailscale#https-support (i.e., that the native TLS integration doesn't work and you need to use `tailscale+tls` instead.

In particular, I'm hoping to have a single server run as a bidirectional HTTP proxy (serve a local service over `tailscale+tls` and also provide a gateway for that service to contact other services on the tailnet)
