### ISSUE TITLE
Question: How to correctly configure reverse_proxy for a TLS upstream

### ISSUE THREAD

**Issue by t0xa** [tailscale/caddy-tailscale#25]
Hello!

Thank you for this incredible project.

Consider following snippet:
```
:80 {
   reverse_proxy https://proxmoxvox.ts.net:8006 {
       transport tailscale
   }
}
```
Error message:
```
Error: adapting config using caddyfile: parsing caddyfile tokens for 'reverse_proxy': upstreams are configured for HTTPS but transport module does not support TLS: *tscaddy.TailscaleCaddyTransport, at Caddyfile:4
```

I understand that this limitation related to https://github.com/tailscale/caddy-tailscale#https-support  but what would be the right syntax?

Thanks!

**Comment by willnorris** [comment]
we hadn't properly added TLS support for the transport.  That should be fixed now.
