### ISSUE TITLE
[Feature Request] Make the caddy-tailscale to go through quic/http3/udp

### ISSUE THREAD

**Issue by diyism** [tailscale/caddy-tailscale#33]
I've used the naiveproxy for many years (https://github.com/klzgrad/forwardproxy/tree/naive),
It uses
caddy web server(naive forwardproxy plugin to padding and multiplexing traffic) + chromium's network stack client
to camouflage traffic with strong censorship resistence,
and it can use http3/quic/udp to provide the best bandwidth and to penetrate the NAT.
(https://github.com/klzgrad/naiveproxy/issues/175#issuecomment-819443385)

I'm thinking could the caddy-tailscale support http3 ?
So that the caddy-tailscale network can realize strong censorship resistence.

**Comment by willnorris** [comment]
caddy-tailscale should now support HTTP3.  Tailscale uses wireguard to encrypt all peer connections, but makes no attempt to disguise that traffic.  So anything beyond this basic HTTP3 support is likely to be beyond the scope of this project.

I'll close this as completed, but feel free to reopen or file a new issue if the HTTP3 support isn't working.

**Comment by diyism** [comment]
Amazing, great thanks to you!
