### ISSUE TITLE
Unable to build from master; unknown Caddy v2 revision

### ISSUE THREAD

**Issue by gbraad** [tailscale/caddy-tailscale#9]
Current master references an unknown revision of Caddy v2

https://github.com/tailscale/caddy-tailscale/blob/57178f8d1cb259289508e853533c1d173b0614ed/go.mod#L6

```
2023/03/03 07:53:06 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/tailscale/caddy-tailscale github.com/caddyserver/caddy/v2 
go: github.com/caddyserver/caddy/v2@v2.5.3-0.20220831215348-67098e5cbd68: invalid version: unknown revision 67098e5cbd68
2023/03/03 07:53:06 [FATAL] exit status 1
```

```
$ go list -m -u github.com/caddyserver/caddy/v2\
go: github.com/caddyserver/caddy/v2@v2.5.3-0.20220831215348-67098e5cbd68: invalid version: unknown revision 67098e5cbd68
```

**Comment by mholt** [comment]
That version definitely exists: https://github.com/caddyserver/caddy/pull/5002/commits/67098e5cbd68b4ad028905d4f2ea2e881c8fbf0d

I suspect a bug in the go tool. We've been having a lot of reports of that lately, for various plugins.

**Comment by gbraad** [comment]
Interesting as several environments reported this for me, including gitpod and codespace :-s
I'll update the tool chain and try again. Which version of go did you use?

Note: the vanity url for one of the modules also failed.

**Comment by gbraad** [comment]
With the following changes:

```diff
-	github.com/caddyserver/caddy/v2 v2.5.3-0.20220831215348-67098e5cbd68
-	tailscale.com v1.1.1-0.20220902232949-3344c3b89bd1
+	github.com/caddyserver/caddy/v2 v2.6.4
+	tailscale.com v1.36.2
```

... it builds with `go 1.19`: https://github.com/tailscale/caddy-tailscale/commit/d98a4ffc9acb153eccadf100d02cfc9864ad3e02

```
$ git clone https://github.com/spotsnel/caddy-tailscale
$ go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
$ xcaddy build v2.6.4 --with github.com/tailscale/caddy-tailscale=./caddy-tailscale
```

however, it won't run properly unless further changes are made as mentioned here: https://github.com/tailscale/caddy-tailscale/issues/11#issuecomment-1464165890
